name: CI

on:
  push:
     branches:
        - main

jobs:
  build:
     runs-on: ubuntu-latest
     
     steps:
       - name: Checkout codigo
         uses: actions/checkout@v3
        
       - name: Configurar Node.js
         uses: actions/setup-node@v3
         with:
           node-version: 18

       - name: Instalar dependencias
         run: npm install

       - name: Generate Prisma Client
         run: npx prisma generate

       - name: Buildar Projeto
         run: npm run build

       - name: Rodar migrações no Postgres do Render
         run: npx prisma migrate deploy
         env:
            DATABASE_URL: ${{secrets.DATABASE_URL}}  

       - name: run seed
         env:
           DATABASE_URL: ${{secrets.DATABASE_URL}}
         run: npx prisma db seed   

         
     