name: CI

on:
  push:
     branches:
        - main

jobs:
  build:
     runs-on: ubuntu-latest
     
     steps:
       - name: Checkout codigo
         uses: actions/checkout@v3
        
       - name: Configurar Node.js
         uses: actions/setup-node@v3
         with:
           node-version: 18

       - name: Instalar dependencias
         run: npm install

       - name: Buldar Projeto
         run: npm run build

       - name: Rodar testes
         run: npm test    
     